_target_: src.datamodules.HeroImagesDataModule
data_dir: ${paths.data_dir}hero_images/
train_dataset_path: ${paths.data_dir}train_dataset.pt
val_dataset_path: ${paths.data_dir}val_dataset.pt
batch_size: 32
# train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 0
pin_memory: False
